export const HELP_TEXT = [
  "Threadwise commands",
  "",
  "/idea <text> - save and structure an idea",
  "/note <text> - save and clean a note for later recall",
  "/note NOTE-1 - show a saved note",
  "/notes - list recent notes",
  "/notes <query> - search saved notes",
  "/note-analysis - analyze your notekeeping style",
  "/add <task> - add a task and keep reminding me until done",
  "/remind <when> | <task> - remind at a specific time",
  "/tasks - list open tasks with active numbers",
  "/task <1 or TASK-1> - show task details",
  "/done <1 or TASK-1> - complete a task",
  "/snooze <1 or TASK-1> 1h - snooze a task",
  "/cancel <1 or TASK-1> - cancel a task",
  "/delete <1 or TASK-1> - alias for /cancel",
  "/relationship <situation> - get balanced relationship guidance",
  "/reflect <situation> - alias for /relationship",
  "/search <query> - semantic search across saved items",
  "/score <IDEA-1> - score an idea with market notes and dos/donts",
  "/brief <IDEA-1> - create a Codex/Claude Code implementation prompt",
  "/calendar <1 or TASK-1> - get calendar export options for a dated task",
  "/settings - show settings",
  "/settings interval 180 - set reminder interval in minutes",
  "/settings timezone Asia/Singapore - set display timezone",
  "/settings quiet 22:00 08:00 - set quiet hours",
  "/settings max 5 - set daily reminder cap",
  "/settings digest on - use shorter reminder messages",
  "",
  "You can also send a normal message. I will classify it and ask before saving."
].join("\n");
