import { bold, code } from "../utils/html";

export const HELP_TEXT = [
  bold("Threadwise commands"),
  "",
  bold("Capture"),
  `${code("/idea <text>")} - save and structure an idea`,
  `${code("/note <text>")} - save and clean a note for later recall`,
  `${code("/add <task>")} - add a task and keep reminding me until done`,
  `${code("/remind <when> | <task>")} - remind at a specific time`,
  "",
  bold("Review"),
  `${code("/tasks")} - list open tasks with active numbers and buttons`,
  `${code("/task <1 or TASK-1>")} - show task details`,
  `${code("/ideas")} - list saved ideas with buttons`,
  `${code("/review")} - compact review of tasks, notes, and ideas`,
  `${code("/search <query>")} - semantic search across saved items`,
  `${code("/search done <query>")} - search completed tasks`,
  `${code("/search notes <query>")} - search only notes; also works with tasks and ideas`,
  `${code("/pins")} - show pinned tasks, notes, and ideas`,
  "",
  bold("Finish"),
  `${code("/done <1 or TASK-1>")} - complete a task`,
  `${code("/snooze <1 or TASK-1> 1h")} - snooze a task`,
  `${code("/reschedule <1 or TASK-1> <when>")} - move a dated task`,
  `${code("/cancel <1 or TASK-1>")} - cancel a task`,
  `${code("/delete <1 or TASK-1>")} - alias for cancel`,
  `${code("/undo")} - reverse the last supported change`,
  `${code("/edit note 2 body <text>")} - edit note body; also works with task details and idea concept`,
  `${code("/rename <1, note 2, or IDEA-1> <title>")} - rename a task, note, or idea`,
  `${code("/pin <1 or ID>")} - pin an item; /star works too`,
  `${code("/unpin <1 or ID>")} - remove a pin`,
  "",
  bold("Notes"),
  `${code("/notes")} - list recent notes`,
  `${code("/notes <query>")} - search saved notes`,
  `${code("/note NOTE-1")} - show a saved note`,
  `${code("/note-analysis")} - analyze your notekeeping style`,
  `${code("/merge notes 1 2 3")} - preview a merged note, then confirm or retry`,
  `${code("/archived notes")} - browse archived notes; also works with ideas and tasks`,
  `${code("/restore NOTE-1")} - restore an archived item`,
  "",
  bold("Ideas"),
  `${code("/ideas <1 or IDEA-1>")} - show a saved idea`,
  `${code("/score IDEA-1")} - score an idea`,
  `${code("/brief IDEA-1")} - create a Codex/Claude Code implementation prompt`,
  "",
  bold("Calendar"),
  `${code("/calendar <1 or TASK-1>")} - get calendar export options for a dated task`,
  "",
  bold("Settings"),
  `${code("/settings")} - show settings`,
  `${code("/settings interval 180")} - set reminder interval in minutes`,
  `${code("/settings timezone Asia/Singapore")} - set display timezone`,
  `${code("/settings quiet 22:00 08:00")} - set quiet hours`,
  `${code("/settings quiet off")} - turn off quiet hours`,
  `${code("/settings max 5")} - set daily reminder cap`,
  `${code("/settings due-nudge 3")} - start dated reminders early and repeat every N minutes`,
  `${code("/settings digest on")} - use shorter reminder messages`,
  "",
  "You can also send a normal message. Clear tasks, notes, ideas, and command-like requests such as merge notes 1 2 3 are handled directly; use /undo if I guessed wrong."
].join("\n");
